print('what is your name?')
name = input()
print('what is your age?')
age = input()
print('what city do you live in?')
city = input()
print('what is your favourite number?')
number = input()
print("------YOUR PROFILE------")
print('Name: ' + name)
print('name in UPPERCASE = ' + name.upper())
print('name in lowercase = ' + name.lower())
print('name in Titlecase = ' + name.title())
print('Number of charater in your name = ' + str(len(name)))


print('city: ' + city)
print('does your city name has "a" in it? ' + str('a' in city))
print('postion of a in your city : ' +(str(city.find('a'))))
print('age: ' + age)
print("age in five years be " +str(int(age)+5))
print("your favourte number "+str(int(number)))
print("is your favourte number greater then 10? " +str(int(number)>10))
print("square of youre favourte number is "+str(int(number)*2))
print("-------SUMMARY-------")
n=len(name)
print('number of charaters your name has ='   +str(n ))

